name: Build PlatformIO project
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Setup PlatformIO in PATH
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1
      
      # Create secrets.h
      - name: Create secrets.h
        run: |
          echo '#define DB_USER "${{ secrets.DB_USER }}"' > src/secrets.h
          echo '#define DB_PASS "${{ secrets.DB_PASS }}"' >> src/secrets.h
      
      # Build the PlatformIO project
      - name: Build PlatformIO project
        run: pio run
